server:
    port: 8080
    servlet:
        context-path: /todo

spring:
    datasource:
        url: "jdbc:postgresql://localhost:5432/postgres"
        username: postgres
        password: 123456

    jpa:
        hibernate:
            ddl-auto: update
        show_sql: true